### PR TITLE
Fixed #2

### LINKED ISSUE #2: properly clean up allocated instructions
Currently in the dodo codebase we have instances of
`i = new_instruction(PRINT);`
where we then store `i` in the list of instructions, these are not cleaned up on program exit.

You can see valgrind listing each instance of this by running `make test`:

```
chris@Ox1b dodo(master)-> make test
Running test.sh
/usr/bin/valgrind

Writing file

Running dodo
==29503== Memcheck, a memory error detector
==29503== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==29503== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==29503== Command: ./dodo tmp_testing_file
==29503== 
'hello world how are you mutter mutter sl/ash
'
'hello'
==29503== 
==29503== HEAP SUMMARY:
==29503==     in use at exit: 320 bytes in 10 blocks
==29503==   total heap usage: 13 allocs, 3 frees, 2,013 bytes allocated
==29503== 
==29503== 32 bytes in 1 blocks are still reachable in loss record 1 of 5
==29503==    at 0x4C272B8: calloc (vg_replace_malloc.c:566)
==29503==    by 0x400B4D: new_instruction (dodo.c:71)
==29503==    by 0x40135A: parse_quit (dodo.c:426)
==29503==    by 0x40164B: parse (dodo.c:556)
==29503==    by 0x401CE3: main (dodo.c:918)
==29503== 
==29503== 64 bytes in 2 blocks are still reachable in loss record 2 of 5
==29503==    at 0x4C272B8: calloc (vg_replace_malloc.c:566)
==29503==    by 0x400B4D: new_instruction (dodo.c:71)
==29503==    by 0x400F9E: parse_print (dodo.c:291)
==29503==    by 0x4014C5: parse (dodo.c:500)
==29503==    by 0x401CE3: main (dodo.c:918)
==29503== 
==29503== 64 bytes in 2 blocks are still reachable in loss record 3 of 5
==29503==    at 0x4C272B8: calloc (vg_replace_malloc.c:566)
==29503==    by 0x400B4D: new_instruction (dodo.c:71)
==29503==    by 0x40108F: parse_byte (dodo.c:326)
==29503==    by 0x401513: parse (dodo.c:511)
==29503==    by 0x401CE3: main (dodo.c:918)
==29503== 
==29503== 64 bytes in 2 blocks are still reachable in loss record 4 of 5
==29503==    at 0x4C272B8: calloc (vg_replace_malloc.c:566)
==29503==    by 0x400B4D: new_instruction (dodo.c:71)
==29503==    by 0x401241: parse_write (dodo.c:387)
==29503==    by 0x4015FD: parse (dodo.c:544)
==29503==    by 0x401CE3: main (dodo.c:918)
==29503== 
==29503== 96 bytes in 3 blocks are still reachable in loss record 5 of 5
==29503==    at 0x4C272B8: calloc (vg_replace_malloc.c:566)
==29503==    by 0x400B4D: new_instruction (dodo.c:71)
==29503==    by 0x40118D: parse_expect (dodo.c:362)
==29503==    by 0x4015AF: parse (dodo.c:533)
==29503==    by 0x401CE3: main (dodo.c:918)
==29503== 
==29503== LEAK SUMMARY:
==29503==    definitely lost: 0 bytes in 0 blocks
==29503==    indirectly lost: 0 bytes in 0 blocks
==29503==      possibly lost: 0 bytes in 0 blocks
==29503==    still reachable: 320 bytes in 10 blocks
==29503==         suppressed: 0 bytes in 0 blocks
==29503== 
==29503== For counts of detected and suppressed errors, rerun with: -v
==29503== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)

Comparing output

All green

Removing temporary file
```

### PR DESCRIPTION
**Pull request by phillid**

### CODE REVIEW

**Comment by chrisosaurus** [comment]
@phillid thanks again for your interest.

What happens if we hit `EXIT` in the case of an error?
we cannot guarantee that p.start is non-null, and so the deref `now->next` could be deref of a null pointer.

Some changes I would appreciate:
- consideration of the above mention error case
- commit message explaining what you are fixing (as currently it has no meaning without github)
- initialising those two new variables to 0 (defensive programming), and one variable per line (trying to keep a consistent style)
- a comment above the cleanup block explaining what you are doing.

You can make changes, add them and (`git add`), then ammend your commit (`git commit --amend`), and then force push (`git push --force origin master:master`) which will update this PR.

**Comment by phillid** [comment]
@mkfifo, thanks for the hint, I hadn't noticed that, all fixed

**Comment by chrisosaurus** [comment]
@phillid thanks for that, looking good!

**Comment by chrisosaurus** [comment]
@phillid just noticed that some tabs snuck in around the indenting of the comment characters https://github.com/mkfifo/dodo/pull/3/files#diff-1c67fed3903b9b87e70ec8f7e94f090fR943

I have pushed a commit to strip these.

Thanks again!

**Pull request merged**
